module.exports = {
    title: 'Related Content',
    context: {
        layoutGrid: true,
        class: 'layout-grid',
        items: [
            {
                link: '#',
                img: '/assets/images/cms/placeholder.svg',
                title: 'Title 01',
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem molestias natus similique eaque deserunt eligendi, doloribus asperiores? Voluptatum mollitia rem perferendis amet incidunt quo architecto doloribus provident excepturi. Aliquam laborum cupiditate autem iure laudantium nisi fugit voluptatem commodi esse distinctio!',
                button: 'Button Title',
            },
            {
                link: '#',
                img: '/assets/images/cms/placeholder.svg',
                title: 'Title 02',
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem molestias natus similique eaque deserunt eligendi, doloribus asperiores? Voluptatum mollitia rem perferendis amet incidunt quo architecto doloribus provident excepturi. Aliquam laborum cupiditate autem iure laudantium nisi fugit voluptatem commodi esse distinctio!',
                button: 'Button Title',
            },
            {
                link: '#',
                img: '/assets/images/cms/placeholder.svg',
                title: 'Title 03',
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem molestias natus similique eaque deserunt eligendi, doloribus asperiores? Voluptatum mollitia rem perferendis amet incidunt quo architecto doloribus provident excepturi. Aliquam laborum cupiditate autem iure laudantium nisi fugit voluptatem commodi esse distinctio!',
                button: 'Button Title',
            },
            {
                link: '#',
                img: '/assets/images/cms/placeholder.svg',
                title: 'Title 04',
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem molestias natus similique eaque deserunt eligendi, doloribus asperiores? Voluptatum mollitia rem perferendis amet incidunt quo architecto doloribus provident excepturi. Aliquam laborum cupiditate autem iure laudantium nisi fugit voluptatem commodi esse distinctio!',
                button: 'Button Title',
            },
            {
                link: '#',
                img: '/assets/images/cms/placeholder.svg',
                title: 'Title 05',
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem molestias natus similique eaque deserunt eligendi, doloribus asperiores? Voluptatum mollitia rem perferendis amet incidunt quo architecto doloribus provident excepturi. Aliquam laborum cupiditate autem iure laudantium nisi fugit voluptatem commodi esse distinctio!',
                button: 'Button Title',
            },
            {
                link: '#',
                img: '/assets/images/cms/placeholder.svg',
                title: 'Title 06',
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem molestias natus similique eaque deserunt eligendi, doloribus asperiores? Voluptatum mollitia rem perferendis amet incidunt quo architecto doloribus provident excepturi. Aliquam laborum cupiditate autem iure laudantium nisi fugit voluptatem commodi esse distinctio!',
                button: 'Button Title',
            },
            {
                link: '#',
                img: '/assets/images/cms/placeholder.svg',
                title: 'Title 07',
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem molestias natus similique eaque deserunt eligendi, doloribus asperiores? Voluptatum mollitia rem perferendis amet incidunt quo architecto doloribus provident excepturi. Aliquam laborum cupiditate autem iure laudantium nisi fugit voluptatem commodi esse distinctio!',
                button: 'Button Title',
            },
        ],
    },
    variants: [
        {
            title: 'Ticker',
            context: {
                layoutTicker: true,
                class: 'layout-ticker',
                items: [
                    {
                        link: '#',
                        img: '/assets/images/cms/placeholder.svg',
                        title: 'Title 01',
                        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem molestias natus similique eaque deserunt eligendi, doloribus asperiores? Voluptatum mollitia rem perferendis amet incidunt quo architecto doloribus provident excepturi. Aliquam laborum cupiditate autem iure laudantium nisi fugit voluptatem commodi esse distinctio!',
                        button: 'Button Title',
                    },
                    {
                        link: '#',
                        img: '/assets/images/cms/placeholder.svg',
                        title: 'Title 02',
                        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem molestias natus similique eaque deserunt eligendi, doloribus asperiores? Voluptatum mollitia rem perferendis amet incidunt quo architecto doloribus provident excepturi. Aliquam laborum cupiditate autem iure laudantium nisi fugit voluptatem commodi esse distinctio!',
                        button: 'Button Title',
                    },
                    {
                        link: '#',
                        img: '/assets/images/cms/placeholder.svg',
                        title: 'Title 03',
                        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem molestias natus similique eaque deserunt eligendi, doloribus asperiores? Voluptatum mollitia rem perferendis amet incidunt quo architecto doloribus provident excepturi. Aliquam laborum cupiditate autem iure laudantium nisi fugit voluptatem commodi esse distinctio!',
                        button: 'Button Title',
                    },
                    {
                        link: '#',
                        img: '/assets/images/cms/placeholder.svg',
                        title: 'Title 04',
                        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem molestias natus similique eaque deserunt eligendi, doloribus asperiores? Voluptatum mollitia rem perferendis amet incidunt quo architecto doloribus provident excepturi. Aliquam laborum cupiditate autem iure laudantium nisi fugit voluptatem commodi esse distinctio!',
                        button: 'Button Title',
                    },
                    {
                        link: '#',
                        img: '/assets/images/cms/placeholder.svg',
                        title: 'Title 05',
                        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem molestias natus similique eaque deserunt eligendi, doloribus asperiores? Voluptatum mollitia rem perferendis amet incidunt quo architecto doloribus provident excepturi. Aliquam laborum cupiditate autem iure laudantium nisi fugit voluptatem commodi esse distinctio!',
                        button: 'Button Title',
                    },
                    {
                        link: '#',
                        img: '/assets/images/cms/placeholder.svg',
                        title: 'Title 06',
                        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem molestias natus similique eaque deserunt eligendi, doloribus asperiores? Voluptatum mollitia rem perferendis amet incidunt quo architecto doloribus provident excepturi. Aliquam laborum cupiditate autem iure laudantium nisi fugit voluptatem commodi esse distinctio!',
                        button: 'Button Title',
                    },
                    {
                        link: '#',
                        img: '/assets/images/cms/placeholder.svg',
                        title: 'Title 07',
                        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem molestias natus similique eaque deserunt eligendi, doloribus asperiores? Voluptatum mollitia rem perferendis amet incidunt quo architecto doloribus provident excepturi. Aliquam laborum cupiditate autem iure laudantium nisi fugit voluptatem commodi esse distinctio!',
                        button: 'Button Title',
                    },
                    {
                        link: '#',
                        img: '/assets/images/cms/placeholder.svg',
                        title: 'Title 07',
                        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem molestias natus similique eaque deserunt eligendi, doloribus asperiores? Voluptatum mollitia rem perferendis amet incidunt quo architecto doloribus provident excepturi. Aliquam laborum cupiditate autem iure laudantium nisi fugit voluptatem commodi esse distinctio!',
                        button: 'Button Title',
                    },
                ],
            },
        },
        {
            title: 'Ticker Has 2 Rows',
            context: {
                layoutTicker: true,
                class: 'layout-ticker has-2-rows',
                items: [
                    {
                        link: '#',
                        img: '/assets/images/cms/placeholder.svg',
                        title: 'Title 01',
                        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem molestias natus similique eaque deserunt eligendi, doloribus asperiores? Voluptatum mollitia rem perferendis amet incidunt quo architecto doloribus provident excepturi. Aliquam laborum cupiditate autem iure laudantium nisi fugit voluptatem commodi esse distinctio!',
                        button: 'Button Title',
                    },
                    {
                        link: '#',
                        img: '/assets/images/cms/placeholder.svg',
                        title: 'Title 02',
                        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem molestias natus similique eaque deserunt eligendi, doloribus asperiores? Voluptatum mollitia rem perferendis amet incidunt quo architecto doloribus provident excepturi. Aliquam laborum cupiditate autem iure laudantium nisi fugit voluptatem commodi esse distinctio!',
                        button: 'Button Title',
                    },
                    {
                        link: '#',
                        img: '/assets/images/cms/placeholder.svg',
                        title: 'Title 03',
                        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem molestias natus similique eaque deserunt eligendi, doloribus asperiores? Voluptatum mollitia rem perferendis amet incidunt quo architecto doloribus provident excepturi. Aliquam laborum cupiditate autem iure laudantium nisi fugit voluptatem commodi esse distinctio!',
                        button: 'Button Title',
                    },
                    {
                        link: '#',
                        img: '/assets/images/cms/placeholder.svg',
                        title: 'Title 04',
                        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem molestias natus similique eaque deserunt eligendi, doloribus asperiores? Voluptatum mollitia rem perferendis amet incidunt quo architecto doloribus provident excepturi. Aliquam laborum cupiditate autem iure laudantium nisi fugit voluptatem commodi esse distinctio!',
                        button: 'Button Title',
                    },
                    {
                        link: '#',
                        img: '/assets/images/cms/placeholder.svg',
                        title: 'Title 05',
                        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem molestias natus similique eaque deserunt eligendi, doloribus asperiores? Voluptatum mollitia rem perferendis amet incidunt quo architecto doloribus provident excepturi. Aliquam laborum cupiditate autem iure laudantium nisi fugit voluptatem commodi esse distinctio!',
                        button: 'Button Title',
                    },
                    {
                        link: '#',
                        img: '/assets/images/cms/placeholder.svg',
                        title: 'Title 06',
                        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem molestias natus similique eaque deserunt eligendi, doloribus asperiores? Voluptatum mollitia rem perferendis amet incidunt quo architecto doloribus provident excepturi. Aliquam laborum cupiditate autem iure laudantium nisi fugit voluptatem commodi esse distinctio!',
                        button: 'Button Title',
                    },
                    {
                        link: '#',
                        img: '/assets/images/cms/placeholder.svg',
                        title: 'Title 07',
                        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem molestias natus similique eaque deserunt eligendi, doloribus asperiores? Voluptatum mollitia rem perferendis amet incidunt quo architecto doloribus provident excepturi. Aliquam laborum cupiditate autem iure laudantium nisi fugit voluptatem commodi esse distinctio!',
                        button: 'Button Title',
                    },
                    {
                        link: '#',
                        img: '/assets/images/cms/placeholder.svg',
                        title: 'Title 07',
                        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem molestias natus similique eaque deserunt eligendi, doloribus asperiores? Voluptatum mollitia rem perferendis amet incidunt quo architecto doloribus provident excepturi. Aliquam laborum cupiditate autem iure laudantium nisi fugit voluptatem commodi esse distinctio!',
                        button: 'Button Title',
                    },
                ],
            },
        },
    ]
};
